#!/bin/bash

set -e

tmpfile=$(mktemp)
if [ ! -w $tmpfile ] ; then
        echo "Failed to create tmp file" >&2
        exit 0
fi

trap "rm -rf $tmpfile" EXIT # cleanup if aborted

RULESET="define concat-set-variable = { 10.10.10.10 . 25, 10.10.10.10 . 143 }

table inet forward {
	set concat-set-variable {
		type ipv4_addr . inet_service
		elements = \$concat-set-variable
	}
}"

echo "$RULESET" > $tmpfile
$NFT -f $tmpfile
