#!/bin/bash

set -e

tmpfile=$(mktemp)
if [ ! -w $tmpfile ] ; then
        echo "Failed to create tmp file" >&2
        exit 0
fi

trap "rm -rf $tmpfile" EXIT # cleanup if aborted

RULESET="define whitelist_v4 = { 1.1.1.1 }

table inet filter {
	set whitelist_v4 { type ipv4_addr; }
}
add element inet filter whitelist_v4 \$whitelist_v4
"

echo "$RULESET" > $tmpfile
$NFT -f $tmpfile
