#!/bin/bash

# tests for Netfilter bug #965 and the related fix
# (regarding rule management with a given position/handle spec)

set -e
$NFT add table t
$NFT add chain t c
# kernel ENOENT
$NFT delete rule t c handle 3333 2>/dev/null
echo "E: missing kernel ENOENT" >&2
