#!/bin/bash

set -e

$NFT add table x
$NFT add map x y { type ipv4_addr : ipv4_addr\; flags timeout\; }

EXPECTED="table ip x {
	map y {
		type ipv4_addr : ipv4_addr
		flags timeout
	}
}"

GET="$($NFT list ruleset)"

if [ "$EXPECTED" != "$GET" ] ; then
	DIFF="$(which diff)"
	[ -x $DIFF ] && $DIFF -u <(echo "$EXPECTED") <(echo "$GET")
	exit 1
fi
