#!/bin/bash

# list table only show table asked for

EXPECTED="table ip test {
}"

set -e

$NFT add table test
$NFT add table test2

GET="$($NFT list table test)"
if [ "$EXPECTED" != "$GET" ] ; then
	DIFF="$(which diff)"
	[ -x $DIFF ] && $DIFF -u <(echo "$EXPECTED") <(echo "$GET")
	exit 1
fi

