#!/bin/bash

# This testcase checks that we can load a ruleset twice in a row.
# bug --> Error: interval overlaps with an existing one

set -e

tmpfile=$(mktemp)
if [ ! -w $tmpfile ] ; then
        echo "Failed to create tmp file" >&2
        exit 0
fi

trap "rm -rf $tmpfile" EXIT # cleanup if aborted

RULESET="flush ruleset
table inet t {
	set s { type ipv4_addr; flags interval; }
}

add element inet t s {
	192.168.0.1/24,
}"

echo "$RULESET" > $tmpfile
$NFT -f $tmpfile
$NFT -f $tmpfile
