#!/bin/bash

# test adding many sets elements

HOWMANY=255

tmpfile=$(mktemp)
if [ ! -w $tmpfile ] ; then
	echo "Failed to create tmp file" >&2
	exit 0
fi

trap "rm -rf $tmpfile" EXIT # cleanup if aborted

generate() {
	echo -n "{"
	for ((i=1; i<=HOWMANY; i++)) ; do
		for ((j=1; j<=HOWMANY; j++)) ; do
			echo -n "10.0.${i}.${j}"
			[ "$i" == "$HOWMANY" ] && [ "$j" == "$HOWMANY" ] && break
			echo -n ", "
		done
	done
	echo -n "}"
}

echo "add table x
add set x y { type ipv4_addr; }
add element x y $(generate)" > $tmpfile

set -e
$NFT -f $tmpfile
