#!/bin/bash

tmpfile=$(mktemp)
if [ ! -w $tmpfile ] ; then
	echo "Failed to create tmp file" >&2
	exit 0
fi

trap "rm -rf $tmpfile" EXIT # cleanup if aborted

echo "flush ruleset
add table t
add chain t c

table inet filter {
  set blacklist_v4 { type ipv4_addr; flags interval; }
}

add element inet filter blacklist_v4 {
192.168.0.1/24,
}" >$tmpfile

$NFT -f $tmpfile

# make sure flush ruleset works right
$NFT -f $tmpfile
