#!/bin/bash

set -e

tmpfile=$(mktemp)
if [ ! -w $tmpfile ] ; then
        echo "Failed to create tmp file" >&2
        exit 0
fi

trap "rm -rf $tmpfile" EXIT # cleanup if aborted

RULESET="add table x
add chain x y
flush ruleset
add table x
add chain x y { type filter hook input priority 0; }
add chain x y { policy drop; }
flush ruleset
add table w
add chain w y { type filter hook output priority 0; }"

echo "$RULESET" > $tmpfile
$NFT -f $tmpfile
if [ $? -ne 0 ] ; then
        echo "E: unable to load good ruleset" >&2
        exit 1
fi

EXPECTED="table ip w {
	chain y {
		type filter hook output priority 0; policy accept;
	}
}"

GET="$($NFT list ruleset)"

if [ "$EXPECTED" != "$GET" ] ; then
	DIFF="$(which diff)"
	[ -x $DIFF ] && $DIFF -u <(echo "$EXPECTED") <(echo "$GET")
	exit 1
fi
